/** Shared catalog fixture for enrich/builder specs — no network, tiny pool. */

import type { Catalog, CatalogCard } from "../src/data/catalog.ts";

export function makeCatalogFixture(): Catalog {
  const cards: CatalogCard[] = [
    {
      id: "SV9-001",
      localId: "001",
      name: "綠毛蟲",
      category: "Pokemon",
      stage: "Basic",
      hp: 50,
      types: ["Grass"],
      attacks: [{ cost: ["Grass"], name: "蟲咬", damage: 20 }],
      weaknesses: [{ type: "Fire", value: "×2" }],
      retreat: 1,
      regulationMark: "I",
      std: true,
      rarity: "Common",
      illustrator: "Shimaris Yukichi",
      dexId: [10],
      description: "別看牠的腳很短。",
      fn: ["heal"],
      set: "SV9",
    },
    {
      id: "S11-001",
      localId: "001",
      name: "綠毛蟲",
      category: "Pokemon",
      stage: "Basic",
      hp: 50,
      types: ["Grass"],
      regulationMark: "F",
      set: "S11",
    },
    {
      id: "SV9-002",
      localId: "002",
      name: "鐵甲蛹",
      category: "Pokemon",
      stage: "Stage1",
      evolveFrom: "綠毛蟲",
      hp: 80,
      types: ["Grass"],
      regulationMark: "I",
      std: true,
      set: "SV9",
    },
    {
      id: "SV9-050",
      localId: "050",
      name: "水水獺",
      category: "Pokemon",
      stage: "Basic",
      hp: 70,
      types: ["Water"],
      regulationMark: "I",
      std: true,
      fn: ["draw"],
      set: "SV9",
    },
    {
      id: "SV9-090",
      localId: "090",
      name: "調換票",
      category: "Trainer",
      trainerType: "Item",
      effect: "數過自己的獎賞卡張數後,全部翻回反面並重洗,放回牌庫下方。",
      regulationMark: "I",
      std: true,
      fn: ["draw"],
      pop: 1,
      set: "SV9",
    },
    {
      id: "SVE-001",
      localId: "001",
      name: "基本草能量",
      category: "Energy",
      energyType: "Basic",
      std: true,
      set: "SVE",
    },
    {
      id: "S8b-075",
      localId: "075",
      name: "仙子伊布VMAX",
      category: "Pokemon",
      stage: "VMAX",
      hp: 310,
      types: ["Psychic"],
      regulationMark: "E",
      set: "S8b",
    },
  ];
  return {
    v: 1,
    lang: "zh-tw",
    source: "TCGdex",
    fetchedAt: "2026-06-12",
    count: cards.length,
    sets: {
      SV9: { name: "對戰搭檔", serie: "朱&紫系列", date: "2025-02-07", official: 100 },
      S11: { name: "舊系列", serie: "劍&盾系列", date: "2022-07-15", official: 100 },
      SVE: { name: "基本能量", serie: "朱&紫系列", date: "2023-03-31", official: 8 },
      S8b: { name: "VMAX 精選", serie: "劍&盾系列", date: "2021-12-03", official: 184 },
    },
    cards,
  };
}
