/**
 * build_evolution.mjs — generate the evolution-chain data the rules engine needs
 * to verify a Rare Candy (神奇糖果) jump-evolution faithfully, from REAL data only.
 *
 * Source: scripts/dex_names.json (PokéAPI species, fetched by fetch_dex_names.mjs):
 *   { "<dexId>": { zh, ja, en, from } }   where `from` = the immediate
 *   pre-evolution's National-Dex id (PokéAPI evolves_from_species), or null.
 *
 * Writes: src/data/evolutionData.ts (a generated TS module — NOT JSON, so it
 * loads identically under Vite, tsc, and Node --experimental-strip-types without
 * any JSON import-attribute friction):
 *   export const FROM:    Record<string, number>  // dexId → preEvo dexId (non-null only)
 *   export const SPECIES: Record<string, number>  // zh / ja / lowercased-en name → dexId
 *
 * `species` lets a card with NO dexId be resolved to its species by exact name
 * match (the catalog only carries dexId on ~40% of Pokémon cards). Exact match
 * only — never fuzzy, so a card we can't resolve is simply not Rare-Candy-able
 * (honest: we never guess a chain).
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const DEX = path.join(ROOT, "scripts", "dex_names.json");
const OUT = path.join(ROOT, "src", "data", "evolutionData.ts");

const dex = JSON.parse(await readFile(DEX, "utf8"));

const from = {};
const species = {};
let collisions = 0;
const addName = (name, id) => {
  if (typeof name !== "string") return;
  const key = name.trim();
  if (key === "") return;
  if (species[key] !== undefined && species[key] !== id) {
    collisions++;
    return; // ambiguous name → drop (never guess)
  }
  species[key] = id;
};

for (const [idStr, rec] of Object.entries(dex)) {
  const id = Number(idStr);
  if (rec.from !== null && rec.from !== undefined) from[id] = rec.from;
  addName(rec.zh, id);
  addName(rec.ja, id);
  if (typeof rec.en === "string") addName(rec.en.toLowerCase(), id);
}

const header =
  "/**\n" +
  " * GENERATED by scripts/build_evolution.mjs — DO NOT EDIT BY HAND.\n" +
  " * Real evolution-chain facts (PokéAPI species, via scripts/dex_names.json):\n" +
  " *   FROM    — dexId → immediate pre-evolution dexId (the species line)\n" +
  " *   SPECIES — exact zh / ja / lowercased-en species name → dexId\n" +
  " * Used by src/data/evolution.ts to verify a Rare Candy jump without guessing.\n" +
  " */\n\n";
const body =
  `export const FROM: Record<string, number> = ${JSON.stringify(from)};\n\n` +
  `export const SPECIES: Record<string, number> = ${JSON.stringify(species)};\n`;
await writeFile(OUT, header + body);
console.log(`evolutionData.ts written: ${Object.keys(from).length} chain links, ${Object.keys(species).length} species names (${collisions} ambiguous names dropped)`);
