/**
 * Real-card catalog (docs/DECISIONS.md 2026-06-12 "真實卡牌目錄").
 *
 * Text-only facts for the full zh-tw (Asia numbering) card pool, generated by
 * scripts/fetch_catalog.mjs from the TCGdex community database with image and
 * pricing fields stripped at the source. Served as a static public/ asset and
 * lazy-fetched on first picker use, so the main bundle never carries it; the
 * service worker makes it offline after one load.
 *
 * The catalog is an assist layer: user-typed card identity remains the
 * first-class path everywhere else in the app.
 */

import type { NewCardInput } from "../state/deckStore.ts";

export interface CatalogAttack {
  cost?: string[];
  name: string;
  effect?: string;
  damage?: number | string;
}

export interface CatalogAbility {
  type?: string;
  name: string;
  effect?: string;
}

export interface CatalogTypeValue {
  type: string;
  value?: string;
}

export interface CatalogCard {
  id: string;
  localId: string;
  name: string;
  category: "Pokemon" | "Trainer" | "Energy";
  stage?: string;
  suffix?: string;
  evolveFrom?: string;
  hp?: number;
  types?: string[];
  attacks?: CatalogAttack[];
  abilities?: CatalogAbility[];
  weaknesses?: CatalogTypeValue[];
  resistances?: CatalogTypeValue[];
  retreat?: number;
  /** Trainer / Energy card rule text. */
  effect?: string;
  trainerType?: string;
  energyType?: string;
  regulationMark?: string;
  /** Standard / Expanded legality (absent = false). */
  std?: boolean;
  exp?: boolean;
  rarity?: string;
  illustrator?: string;
  dexId?: number[];
  /** Pokédex flavor text. */
  description?: string;
  item?: { name: string; effect?: string };
  /** 人性化功能標籤 — deterministic keyword tags over the official card text
   *  (pipeline classify(); keys: search/draw/accel/heal/disrupt/gust/recover/
   *  protect/boost/attacker/ability). */
  fn?: string[];
  /** 熱門排名 (1 = hottest) from REAL tournament inclusion rate (Limitless,
   *  scripts/fetch_meta.mjs); lower sorts first, absent sorts last. */
  pop?: number;
  /** Real inclusion rate: % of sampled tournament decks that play this card. */
  usage?: number;
  /** Trilingual names (scripts/fetch_names.mjs): nameZh complete, nameJa
   *  SV-era, nameEn partial. `name` stays the canonical storage key. */
  nameZh?: string;
  nameJa?: string;
  nameEn?: string;
  set: string | null;
}

export interface CatalogSet {
  name: string;
  serie: string | null;
  date: string | null;
  official: number | null;
}

export interface Catalog {
  v: number;
  lang: string;
  source: string;
  fetchedAt: string;
  count: number;
  /** Real rotation rule the pipeline derived `std` from (official source). */
  format?: { standard: string[]; effective: string; source?: string };
  /** Newest set in the snapshot — honesty line for data freshness. */
  newest?: { id: string; name: string; date: string | null };
  /** Real popularity sample provenance (Limitless tournament decklists). */
  meta?: {
    source: string;
    sampleDecks: number;
    tournaments: number;
    dateFrom: string;
    dateTo: string;
  };
  sets: Record<string, CatalogSet>;
  cards: CatalogCard[];
  /** English-species → zh map (scripts/embed_en_zh.mjs, from the official dex)
   *  so deck rows saved with an English Pokémon name can be localized even when
   *  that card carries no nameEn field. Keys are lowercased English species. */
  dexEnZh?: Record<string, string>;
  /** Verified Trainer/Energy staple EN → zh (scripts/name_bridge.json). Keys
   *  lowercased; unambiguous staples only (ambiguous names omitted, not guessed). */
  trainerEnZh?: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Loading — module-level promise cache; tests inject a fixture instead.

let catalogPromise: Promise<Catalog> | null = null;

export function loadCatalog(): Promise<Catalog> {
  if (catalogPromise === null) {
    catalogPromise = fetch(`${import.meta.env.BASE_URL}catalog/cards-zh-Hant.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`catalog HTTP ${res.status}`);
        return res.json() as Promise<Catalog>;
      })
      .catch((err: unknown) => {
        catalogPromise = null; // allow retry after a failed load
        throw err;
      });
  }
  return catalogPromise;
}

/** Test hook: replace (or clear) the catalog without touching the network. */
export function setCatalogForTests(catalog: Catalog | null): void {
  catalogPromise = catalog === null ? null : Promise.resolve(catalog);
}

// ---------------------------------------------------------------------------
// Trilingual display (owner request 2026-06-13): show the card name in the
// chosen language; the data (nameZh / nameJa / nameEn) is built by
// scripts/fetch_names.mjs. Missing a language → fall back so a name always
// shows (never blank), preferring the requested language first.

export type NameLang = "zh" | "en" | "ja";

/** The card name in the requested language, with a graceful fallback chain. */
export function cardName(card: CatalogCard, lang: NameLang): string {
  const zh = card.nameZh ?? card.name;
  const ja = card.nameJa;
  const en = card.nameEn;
  if (lang === "ja") return ja ?? zh ?? en ?? card.name;
  if (lang === "en") return en ?? zh ?? ja ?? card.name;
  return zh ?? ja ?? en ?? card.name;
}

/** Whether a card actually carries a name in the requested language (so we can
 *  avoid replacing an English deck name with a Japanese fallback when no real
 *  zh exists yet). */
export function hasLang(card: CatalogCard, lang: NameLang): boolean {
  if (lang === "zh") return card.nameZh !== undefined;
  if (lang === "en") return card.nameEn !== undefined;
  return card.nameJa !== undefined;
}

/** The other two languages (for tri-lingual secondary lines), de-duplicated. */
export function otherNames(card: CatalogCard, primary: NameLang): string[] {
  const primaryName = cardName(card, primary);
  const all: Array<[NameLang, string | undefined]> = [
    ["zh", card.nameZh ?? card.name],
    ["en", card.nameEn],
    ["ja", card.nameJa],
  ];
  const out: string[] = [];
  for (const [lang, name] of all) {
    if (lang === primary || name === undefined || name === primaryName || out.includes(name)) continue;
    out.push(name);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Search

/** Case-insensitive substring search over name and set/number identity. */
export function searchCatalog(catalog: Catalog, query: string, max = 50): CatalogCard[] {
  const q = query.trim().toLowerCase();
  if (q === "") return [];
  const hits: { card: CatalogCard; rank: number }[] = [];
  for (const card of catalog.cards) {
    const name = card.name.toLowerCase();
    const idText = `${card.set ?? ""} ${card.localId} ${card.id}`.toLowerCase();
    let rank: number;
    if (name.startsWith(q)) rank = 0;
    else if (name.includes(q)) rank = 1;
    else if (idText.includes(q)) rank = 2;
    else continue;
    hits.push({ card, rank });
  }
  hits.sort((a, b) => {
    if (a.rank !== b.rank) return a.rank - b.rank;
    // 熱門排前: popular names first, then standard-legal prints, then the
    // newest set, so the playable answer lands on top.
    const pa = a.card.pop ?? Number.MAX_SAFE_INTEGER;
    const pb = b.card.pop ?? Number.MAX_SAFE_INTEGER;
    if (pa !== pb) return pa - pb;
    const aStd = a.card.std === true ? 0 : 1;
    const bStd = b.card.std === true ? 0 : 1;
    if (aStd !== bStd) return aStd - bStd;
    const da = catalog.sets[a.card.set ?? ""]?.date ?? "";
    const db = catalog.sets[b.card.set ?? ""]?.date ?? "";
    if (da !== db) return da < db ? 1 : -1;
    return a.card.id < b.card.id ? -1 : 1;
  });
  return hits.slice(0, max).map((h) => h.card);
}

// ---------------------------------------------------------------------------
// Deck mapping

/** Mulligan math counts 基礎寶可夢 only — never Basic Energy. */
export function isBasicPokemon(card: CatalogCard): boolean {
  return card.category === "Pokemon" && card.stage === "Basic";
}

/**
 * Format-legal for the current Standard (H/I/J). The pipeline's `std` flag IS
 * the verified legality: regulation marks H/I/J plus Basic Energy (which never
 * rotates), per the official asia.pokemon-card.com rotation that drives
 * catalog.format. Single source of truth so the picker, builder and battle
 * sandbox can never offer an illegal card. (Verified 2026-06-14: the only
 * non-H/I std cards are Basic Energy reprints — correct, not a bug.)
 */
export function isFormatLegal(card: CatalogCard): boolean {
  return card.std === true;
}

export function sectionOf(card: CatalogCard): "pokemon" | "trainer" | "energy" {
  if (card.category === "Pokemon") return "pokemon";
  if (card.category === "Energy") return "energy";
  return "trainer";
}

/** A deck-row input carrying everything the catalog knows that the row stores. */
export function toNewCardInput(card: CatalogCard): NewCardInput {
  const mark =
    card.regulationMark !== undefined && /^[A-Z]$/.test(card.regulationMark)
      ? card.regulationMark
      : undefined;
  return {
    name: card.name,
    count: 1,
    isBasic: isBasicPokemon(card),
    section: sectionOf(card),
    ...(card.set !== null ? { set: card.set } : {}),
    number: card.localId,
    ...(mark !== undefined ? { mark } : {}),
    catalogId: card.id,
  };
}

/** 熱門 first, then std-legal prints, then newest set, then id — the order
 *  used by search, the builder grid and name matching. */
export function sortPrints(catalog: Catalog, cards: CatalogCard[]): CatalogCard[] {
  return [...cards].sort((a, b) => {
    const pa = a.pop ?? Number.MAX_SAFE_INTEGER;
    const pb = b.pop ?? Number.MAX_SAFE_INTEGER;
    if (pa !== pb) return pa - pb;
    const aStd = a.std === true ? 0 : 1;
    const bStd = b.std === true ? 0 : 1;
    if (aStd !== bStd) return aStd - bStd;
    const da = catalog.sets[a.set ?? ""]?.date ?? "";
    const db = catalog.sets[b.set ?? ""]?.date ?? "";
    if (da !== db) return da < db ? 1 : -1;
    return a.id < b.id ? -1 : 1;
  });
}

/**
 * Collapse a print-level list to one entry per card NAME (owner request,
 * 2026-06-12): the representative is the best print (popular → std → newest,
 * via sortPrints), and every same-name print is kept for a quick picker. The
 * group order follows the input order of each name's first appearance, so a
 * popularity- or relevance-sorted input stays sorted.
 */
export interface PrintGroup {
  rep: CatalogCard;
  prints: CatalogCard[];
}
export function groupByName(catalog: Catalog, cards: CatalogCard[]): PrintGroup[] {
  const order: string[] = [];
  const byName = new Map<string, CatalogCard[]>();
  for (const c of cards) {
    let g = byName.get(c.name);
    if (g === undefined) {
      g = [];
      byName.set(c.name, g);
      order.push(c.name);
    }
    g.push(c);
  }
  return order.map((name) => {
    const prints = sortPrints(catalog, byName.get(name) as CatalogCard[]);
    return { rep: prints[0] as CatalogCard, prints };
  });
}

/** Per-catalog id → card index, built once per catalog object. */
const idIndexCache = new WeakMap<Catalog, Map<string, CatalogCard>>();
export function cardById(catalog: Catalog, id: string): CatalogCard | null {
  let index = idIndexCache.get(catalog);
  if (index === undefined) {
    index = new Map(catalog.cards.map((c) => [c.id, c]));
    idIndexCache.set(catalog, index);
  }
  return index.get(id) ?? null;
}

/**
 * Resolve a deck row to its catalog card: exact print (set+number) wins;
 * otherwise the best print of the exact (trimmed) name.
 */
export function matchRow(
  catalog: Catalog,
  row: { name: string; set?: string; number?: string },
): CatalogCard | null {
  if (row.set !== undefined && row.number !== undefined) {
    const exact = catalog.cards.find((c) => c.set === row.set && c.localId === row.number);
    if (exact) return exact;
  }
  const name = row.name.trim();
  if (name === "") return null;
  const prints = catalog.cards.filter((c) => c.name === name);
  if (prints.length === 0) return null;
  return sortPrints(catalog, prints)[0] ?? null;
}

/**
 * Reverse index from EVERY known name variant (canonical / zh / ja / en) to the
 * best print carrying it (popular → std → newest). Built once per catalog so a
 * stored deck row — whatever language the import happened to save — can resolve
 * back to its real card for localized display + type color.
 */
const nameIndexCache = new WeakMap<Catalog, Map<string, CatalogCard>>();
function nameIndex(catalog: Catalog): Map<string, CatalogCard> {
  let idx = nameIndexCache.get(catalog);
  if (idx === undefined) {
    idx = new Map();
    const ranked = sortPrints(catalog, catalog.cards); // best print first
    for (const c of ranked) {
      for (const nm of [c.name, c.nameZh, c.nameJa, c.nameEn]) {
        if (nm !== undefined && nm !== "" && !idx.has(nm)) idx.set(nm, c);
      }
    }
    nameIndexCache.set(catalog, idx);
  }
  return idx;
}

/**
 * Resolve a deck row to its catalog card: catalog id → exact print (set+number)
 * → any known name. Used to localize and type-color deck rows that were saved
 * in another language (owner request 2026-06-14).
 */
export function resolveDeckRow(
  catalog: Catalog,
  row: { name: string; set?: string; number?: string; catalogId?: string },
): CatalogCard | null {
  if (row.catalogId !== undefined) {
    const byId = cardById(catalog, row.catalogId);
    if (byId !== null) return byId;
  }
  if (row.set !== undefined && row.number !== undefined) {
    const exact = catalog.cards.find((c) => c.set === row.set && c.localId === row.number);
    if (exact !== undefined) return exact;
  }
  const nm = row.name.trim();
  return nm !== "" ? (nameIndex(catalog).get(nm) ?? null) : null;
}

// English Pokémon name → zh, applying the official affix conventions (mirrors
// scripts/fill_zh_names.mjs). Returns the full localized name plus the bare
// species zh (for a type-color lookup when no exact print exists).
const EN_REGION: Array<[RegExp, string]> = [
  [/^alolan\s+/i, "阿羅拉"],
  [/^galarian\s+/i, "伽勒爾"],
  [/^hisuian\s+/i, "洗翠"],
  [/^paldean\s+/i, "帕底亞"],
];
const EN_SUFFIX = ["ex", "V-UNION", "VMAX", "VSTAR", "V"];

function enNameToZh(catalog: Catalog, name: string): { full: string; base: string } | null {
  const map = catalog.dexEnZh;
  if (map === undefined) return null;
  let s = name.trim();
  let prefix = "";
  let suffix = "";
  const mega = /^mega\s+/i.test(s);
  if (mega) s = s.replace(/^mega\s+/i, "");
  for (const [re, zh] of EN_REGION) {
    if (re.test(s)) {
      prefix = zh;
      s = s.replace(re, "");
      break;
    }
  }
  if (mega) prefix = "超級" + prefix;
  for (const suf of EN_SUFFIX) {
    const re = new RegExp(`\\s*${suf.replace(/-/g, "\\-")}$`, "i");
    if (re.test(s)) {
      suffix = suf === "ex" ? "ex" : suf.toUpperCase();
      s = s.replace(re, "");
      break;
    }
  }
  const base = map[s.trim().toLowerCase()];
  if (base === undefined) return null;
  return { full: `${prefix}${base}${suffix}`, base };
}

/**
 * Localize a deck row for display: resolve to a catalog card and use its name
 * in `lang`; if the row was saved with an English Pokémon name that has no
 * matching card, bridge it through the official dex (owner request 2026-06-14 —
 * "繁中要真係繁中" even for the deck list). Returns the display name plus the
 * best card found (for the type-color accent), or null when nothing resolves.
 */
export function localizeDeckRow(
  catalog: Catalog,
  row: { name: string; set?: string; number?: string; catalogId?: string },
  lang: NameLang,
): { name: string; card: CatalogCard | null } {
  const card = resolveDeckRow(catalog, row);
  if (card !== null && hasLang(card, lang)) return { name: cardName(card, lang), card };
  // English name with no matching card → verified bridges (zh display only).
  const asciiOnly = /[a-zA-Z]/.test(row.name) && !/[一-鿿぀-ヿ]/.test(row.name);
  if (lang === "zh" && asciiOnly) {
    const idx = nameIndex(catalog);
    // Trainer/Energy staples first (exact, verified fact table).
    const staple = catalog.trainerEnZh?.[row.name.trim().toLowerCase()];
    if (staple !== undefined) return { name: staple, card: idx.get(staple) ?? card };
    // Then Pokémon species via the official dex (with affixes).
    const zh = enNameToZh(catalog, row.name);
    if (zh !== null) {
      const card2 = idx.get(zh.full) ?? idx.get(zh.base) ?? card;
      return { name: zh.full, card: card2 };
    }
  }
  return { name: card !== null ? cardName(card, lang) : row.name, card };
}

/** The full tag patch a matched catalog card stamps onto a deck row. */
export function enrichPatch(card: CatalogCard): Omit<NewCardInput, "name" | "count"> {
  const input = toNewCardInput(card);
  return {
    isBasic: input.isBasic,
    section: input.section,
    ...(input.set !== undefined ? { set: input.set } : {}),
    ...(input.number !== undefined ? { number: input.number } : {}),
    ...(input.mark !== undefined ? { mark: input.mark } : {}),
    catalogId: input.catalogId,
  };
}

/** Kind descriptor: stage for Pokémon, trainer type, or energy type. */
export function kindOf(card: CatalogCard): { key: string | null; raw: string } {
  if (card.category === "Pokemon") {
    return card.stage !== undefined
      ? { key: stageKey(card.stage), raw: card.stage }
      : { key: "catalog.cat.pokemon", raw: "Pokemon" };
  }
  if (card.category === "Trainer") {
    return card.trainerType !== undefined
      ? { key: trainerTypeKey(card.trainerType), raw: card.trainerType }
      : { key: "catalog.cat.trainer", raw: "Trainer" };
  }
  return card.energyType !== undefined
    ? { key: energyTypeKey(card.energyType), raw: card.energyType }
    : { key: "catalog.cat.energy", raw: "Energy" };
}

// ---------------------------------------------------------------------------
// Display key mappers — values stay data, labels go through i18n.

const STAGE_KEYS: Record<string, string> = {
  Basic: "catalog.stage.basic",
  Stage1: "catalog.stage.stage1",
  Stage2: "catalog.stage.stage2",
  VMAX: "catalog.stage.vmax",
  VSTAR: "catalog.stage.vstar",
  MEGA: "catalog.stage.mega",
  "LEVEL-UP": "catalog.stage.levelup",
  BREAK: "catalog.stage.break",
};
export function stageKey(stage: string): string | null {
  return STAGE_KEYS[stage] ?? null;
}

const TRAINER_KEYS: Record<string, string> = {
  Item: "catalog.trainer.item",
  Supporter: "catalog.trainer.supporter",
  Stadium: "catalog.trainer.stadium",
  Tool: "catalog.trainer.tool",
};
export function trainerTypeKey(trainerType: string): string | null {
  return TRAINER_KEYS[trainerType] ?? null;
}

const ENERGY_KEYS: Record<string, string> = {
  Basic: "catalog.energy.basic",
  Special: "catalog.energy.special",
  Normal: "catalog.energy.basic",
};
export function energyTypeKey(energyType: string): string | null {
  return ENERGY_KEYS[energyType] ?? null;
}

/** 功能 tags in display order (builder chips, CardVisual). */
export const FN_ORDER = [
  "attacker",
  "ability",
  "search",
  "draw",
  "accel",
  "gust",
  "disrupt",
  "recover",
  "heal",
  "protect",
  "boost",
] as const;

const FN_KEYS: Record<string, string> = {
  search: "catalog.fn.search",
  draw: "catalog.fn.draw",
  accel: "catalog.fn.accel",
  heal: "catalog.fn.heal",
  disrupt: "catalog.fn.disrupt",
  gust: "catalog.fn.gust",
  recover: "catalog.fn.recover",
  protect: "catalog.fn.protect",
  boost: "catalog.fn.boost",
  attacker: "catalog.fn.attacker",
  ability: "catalog.fn.ability",
};
export function fnKey(tag: string): string | null {
  return FN_KEYS[tag] ?? null;
}

const TYPE_KEYS: Record<string, string> = {
  Grass: "catalog.type.grass",
  Fire: "catalog.type.fire",
  Water: "catalog.type.water",
  Lightning: "catalog.type.lightning",
  Psychic: "catalog.type.psychic",
  Fighting: "catalog.type.fighting",
  Darkness: "catalog.type.darkness",
  Metal: "catalog.type.metal",
  Dragon: "catalog.type.dragon",
  Colorless: "catalog.type.colorless",
  Fairy: "catalog.type.fairy",
};
export function typeKey(type: string): string | null {
  return TYPE_KEYS[type] ?? null;
}
