/**
 * Real archetype deck recommendations (docs/06 Phase 11) — generated by
 * scripts/fetch_decks.mjs from public Limitless tournament decklists. Served
 * as a lazy public/ asset; the math layer only ever reads count + isBasic.
 */

import type { NewCardInput } from "../state/deckStore.ts";

export interface DeckCardLine {
  count: number;
  /** zh-tw name where bridgeable, else the English/ja name (honest fallback). */
  name: string;
  isBasic: boolean;
  section: "pokemon" | "trainer" | "energy" | "unknown";
}

export interface DeckBuild {
  event: string;
  date: string;
  players: number;
  online: boolean;
  /** Final placing when known (null = not in the published top cut). */
  placing: number | null;
  total: number;
  cards: DeckCardLine[];
}

export interface Archetype {
  id: string;
  /** Limitless's own archetype name (English carry Pokémon). */
  name: string;
  icons: string[];
  deckCount: number;
  score: number;
  builds: DeckBuild[];
}

export interface DeckData {
  v: number;
  source: string;
  note: string;
  generatedFor: string;
  format: string;
  sampleDecks: number;
  tournaments: number;
  dateFrom: string | null;
  dateTo: string | null;
  archetypes: Archetype[];
}

let decksPromise: Promise<DeckData> | null = null;

export function loadDecks(): Promise<DeckData> {
  if (decksPromise === null) {
    decksPromise = fetch(`${import.meta.env.BASE_URL}catalog/decks-zh-Hant.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`decks HTTP ${res.status}`);
        return res.json() as Promise<DeckData>;
      })
      .catch((err: unknown) => {
        decksPromise = null;
        throw err;
      });
  }
  return decksPromise;
}

/** Test hook: inject (or clear) the deck data without a network call. */
export function setDecksForTests(data: DeckData | null): void {
  decksPromise = data === null ? null : Promise.resolve(data);
}

/** A build's 60 lines as deck-import inputs (math reads count + isBasic). */
export function buildToInputs(build: DeckBuild): NewCardInput[] {
  return build.cards.map((c) => ({
    name: c.name,
    count: c.count,
    isBasic: c.isBasic,
    section: c.section,
  }));
}

/** Field-size tier label (honest: by player count, not official rank). */
export function tierKey(players: number): string {
  if (players >= 128) return "decks.tier.large";
  if (players >= 64) return "decks.tier.mid";
  if (players >= 32) return "decks.tier.small";
  return "decks.tier.local";
}
