/**
 * Real archetype deck recommendations (docs/06 Phase 11) — generated by
 * scripts/fetch_decks.mjs from public Limitless tournament decklists. Served
 * as a lazy public/ asset; the math layer only ever reads count + isBasic.
 */

import type { NewCardInput } from "../state/deckStore.ts";
import { resolveDeckRow, type Catalog } from "./catalog.ts";
import { energyType } from "./typeColors.ts";

export interface DeckCardLine {
  count: number;
  /** zh-tw name where bridgeable, else the English/ja name (honest fallback). */
  name: string;
  isBasic: boolean;
  section: "pokemon" | "trainer" | "energy" | "unknown";
}

export interface DeckBuild {
  event: string;
  date: string;
  players: number;
  online: boolean;
  /** Final placing when known (null = not in the published top cut). */
  placing: number | null;
  total: number;
  cards: DeckCardLine[];
}

export interface Archetype {
  id: string;
  /** Limitless's own archetype name (English carry Pokémon). */
  name: string;
  icons: string[];
  deckCount: number;
  score: number;
  builds: DeckBuild[];
}

export interface DeckData {
  v: number;
  source: string;
  note: string;
  generatedFor: string;
  format: string;
  sampleDecks: number;
  tournaments: number;
  dateFrom: string | null;
  dateTo: string | null;
  archetypes: Archetype[];
}

/**
 * A 系列 (owner request #40 2026-06-15): one or more Limitless archetypes that
 * share the same 主軸 (carry Pokémon) folded into a single column, so the user
 * picks the pairing 路線 (e.g. Dragapult / Dragapult+Dusknoir / Dragapult+
 * Blaziken) within one card instead of scanning four near-identical rows.
 */
export interface DeckSeries {
  /** carry species key, or "@<archId>" for a mechanic-named standalone. */
  id: string;
  /** representative icon slug of the most-played member (for the dex lookup). */
  carryIcon: string;
  /** true = a Pokémon carry (localize via dex); false = a mechanic handle. */
  isCarry: boolean;
  /** variants, most-played first. */
  members: Archetype[];
  /** total decks across all variants of this carry. */
  deckCount: number;
  /** max member score (series ordering). */
  score: number;
}

let decksPromise: Promise<DeckData> | null = null;

export function loadDecks(): Promise<DeckData> {
  if (decksPromise === null) {
    decksPromise = fetch(`${import.meta.env.BASE_URL}catalog/decks-zh-Hant.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`decks HTTP ${res.status}`);
        return res.json() as Promise<DeckData>;
      })
      .catch((err: unknown) => {
        decksPromise = null;
        throw err;
      });
  }
  return decksPromise;
}

/** Test hook: inject (or clear) the deck data without a network call. */
export function setDecksForTests(data: DeckData | null): void {
  decksPromise = data === null ? null : Promise.resolve(data);
}

/** A build's 60 lines as deck-import inputs (math reads count + isBasic). */
export function buildToInputs(build: DeckBuild): NewCardInput[] {
  return build.cards.map((c) => ({
    name: c.name,
    count: c.count,
    isBasic: c.isBasic,
    section: c.section,
  }));
}

/** Field-size tier label (honest: by player count, not official rank). */
export function tierKey(players: number): string {
  if (players >= 128) return "decks.tier.large";
  if (players >= 64) return "decks.tier.mid";
  if (players >= 32) return "decks.tier.small";
  return "decks.tier.local";
}

// ---------------------------------------------------------------------------
// Archetype name localization (owner request 2026-06-14: 牌組推薦 titles must be
// zh in the zh UI). Limitless archetype names are space-separated English
// Pokémon (+ Mega / possessive prefixes / a few descriptors). Pokémon map via
// the official dex (catalog.dexEnZh); unknown tokens stay English (no guessing).

const ARCH_POSSESSIVE: Record<string, string> = {
  "n's": "N之",
  "rocket's": "火箭隊的",
  "team rocket's": "火箭隊的",
  "cynthia's": "竹蘭的",
  "hop's": "赫普的",
  "lillie's": "莉莉艾的",
  "misty's": "小霞的",
  "marnie's": "瑪俐的",
  "iono's": "奇樹的",
  "ethan's": "阿正的",
};
const ARCH_WORD: Record<string, string> = {
  box: "盒組",
  toolbox: "百寶箱",
  lead: "先手",
  basic: "基礎",
  control: "控場",
  mill: "磨牌",
  turbo: "渦輪",
  stall: "拖延",
};

// Curated overrides for archetypes that aren't simply "Pokémon (+Pokémon)":
// names built on an ability / mechanic / community handle, where a per-word
// translation reads wrong (owner feedback 2026-06-15: 「有時主題…可以係以寶可夢
// 特性嚟組既牌組命名」). Keyed by the lowercased Limitless archetype name; the
// owner is the authority on the zh competitive handle. Extend as the meta moves.
const ARCH_OVERRIDE: Record<string, string> = {
  "festival lead": "祭典樂舞",
  "basic box": "太晶Box",
};

/** Localize a Limitless archetype name to zh (Pokémon via the official dex). */
export function localizeArchetype(name: string, catalog: Catalog | null): string {
  const override = ARCH_OVERRIDE[name.trim().toLowerCase()];
  if (override !== undefined) return override;
  const dex = catalog?.dexEnZh;
  if (dex === undefined) return name;
  const words = name.trim().split(/\s+/);
  const parts: string[] = [];
  let prefix = ""; // Mega / possessive that attaches to the next Pokémon
  for (let i = 0; i < words.length; i++) {
    const w = words[i] as string;
    const lw = w.toLowerCase();
    if (lw === "mega") {
      prefix += "超級";
      continue;
    }
    if (ARCH_POSSESSIVE[lw] !== undefined) {
      prefix += ARCH_POSSESSIVE[lw];
      continue;
    }
    // Try a two-word Pokémon (e.g. Raging Bolt, Iron Hands) then one word.
    const two = i + 1 < words.length ? `${lw} ${(words[i + 1] as string).toLowerCase()}` : "";
    if (two !== "" && dex[two] !== undefined) {
      parts.push(prefix + dex[two]);
      prefix = "";
      i += 1;
      continue;
    }
    if (dex[lw] !== undefined) {
      parts.push(prefix + dex[lw]);
      prefix = "";
      continue;
    }
    // Descriptor or unknown.
    parts.push(prefix + (ARCH_WORD[lw] ?? w));
    prefix = "";
  }
  if (prefix !== "") parts.push(prefix); // dangling Mega with no match
  return parts.join(" ");
}

// ---------------------------------------------------------------------------
// 系列 grouping (owner request #40 2026-06-15): fold archetypes that share a
// carry Pokémon into one column with a 路線 picker. Driven by Limitless's own
// icon slugs (icons[0] = the carry), so it's data, not a guess.

// Form suffixes on an icon slug (greninja-mega, starmie-mega). NOT "-bolt" etc.,
// so multi-word species like raging-bolt keep their distinct carry key.
const ICON_FORM = /-(mega|gmax|vmax|vstar|gx|ex|v|tera)$/;

/** Carry species key of an archetype: its lead icon with any form suffix removed. */
function carryKeyOf(arch: Archetype): string {
  return (arch.icons[0] ?? arch.id).replace(ICON_FORM, "");
}

/**
 * Group archetypes into series by shared carry. Mechanic-named archetypes (those
 * with a curated handle override, e.g. 太晶Box / 祭典樂舞) stay standalone — they
 * are an identity of their own, not "a variant of a carry". Series and the
 * variants within each are ordered by real popularity (deck count) descending.
 */
export function groupSeries(archetypes: Archetype[]): DeckSeries[] {
  const byKey = new Map<string, DeckSeries>();
  const order: string[] = [];
  for (const a of archetypes) {
    const mechanic = ARCH_OVERRIDE[a.name.trim().toLowerCase()] !== undefined;
    const key = mechanic ? `@${a.id}` : carryKeyOf(a);
    let s = byKey.get(key);
    if (s === undefined) {
      s = {
        id: key,
        carryIcon: a.icons[0] ?? a.id,
        isCarry: !mechanic,
        members: [],
        deckCount: 0,
        score: 0,
      };
      byKey.set(key, s);
      order.push(key);
    }
    s.members.push(a);
    s.deckCount += a.deckCount;
    if (a.score > s.score) s.score = a.score;
  }
  const series = order.map((k) => byKey.get(k) as DeckSeries);
  const byPopularity = (a: Archetype, b: Archetype) =>
    b.deckCount - a.deckCount || b.score - a.score;
  for (const s of series) {
    s.members.sort(byPopularity);
    s.carryIcon = s.members[0]?.icons[0] ?? s.carryIcon;
  }
  series.sort((a, b) => b.deckCount - a.deckCount || b.score - a.score);
  return series;
}

/**
 * zh display name for a series' carry. A Pokémon carry localizes via the official
 * dex (icon slug → species); a mechanic-named standalone uses its curated handle.
 * Unknown carry → an honest Title-Cased fallback (never a guess).
 */
export function localizeCarry(series: DeckSeries, catalog: Catalog | null): string {
  const first = series.members[0];
  if (!series.isCarry && first !== undefined) return localizeArchetype(first.name, catalog);
  const species = series.carryIcon.replace(ICON_FORM, "").replace(/-/g, " ");
  const zh = catalog?.dexEnZh?.[species];
  if (zh !== undefined) return zh;
  return species.replace(/\b\w/g, (m) => m.toUpperCase());
}

// ---------------------------------------------------------------------------
// Tier affixes on series / variant titles (owner request 2026-06-16: 「係 ex 既
//就應該寫返 ex」). The Limitless archetype name is the bare species; the REAL
// decklist card already carries the tier (多龍巴魯托ex / 超級甲賀忍蛙ex / …), so
// we read the tier straight off the deck — never guessed.

const TIER_SUFFIX = /(ex|VMAX|VSTAR|V)$/i;

/** Bare species: drop the 超級 prefix and the ex / V / VMAX / VSTAR suffix. */
export function stripTier(name: string): string {
  return name.replace(/^超級/, "").replace(TIER_SUFFIX, "").trim();
}

/**
 * Replace each localized Pokémon token in a (space-joined) title with the REAL
 * decklist card name carrying its tier, when a matching card exists among
 * `cardNames` (the build's zh-localized Pokémon names; prefers a tiered match).
 * Descriptors with no matching card pass through unchanged.
 */
export function tierizeName(localized: string, cardNames: string[]): string {
  return localized
    .split(" ")
    .map((tok) => {
      const matches = cardNames.filter((n) => stripTier(n) === tok);
      return (matches.find((n) => n !== tok) ?? matches[0]) ?? tok;
    })
    .join(" ");
}

/**
 * The deck's real type identity (owner request 2026-06-16): the distinct basic-
 * energy types it runs, most-used first. This is what drives the row colour and
 * the energy-type icons — e.g. a Grass-Energy deck reads Grass even when the
 * carry Pokémon (裹蜜蟲 / Dipplin) is Dragon. Special energies map to nothing.
 */
export function deckEnergyTypes(build: DeckBuild | undefined): string[] {
  if (build === undefined) return [];
  const count = new Map<string, number>();
  for (const c of build.cards) {
    if (c.section !== "energy") continue;
    const ty = energyType(c.name);
    if (ty !== null) count.set(ty, (count.get(ty) ?? 0) + c.count);
  }
  return [...count.entries()].sort((a, b) => b[1] - a[1]).map(([ty]) => ty);
}

// ---------------------------------------------------------------------------
// Humanized playstyle / selling-point tags, computed from the deck's REAL card
// functions (the classify() fn tags) — data-driven, not editorial.

export interface DeckTag {
  key: string; // i18n key
  weight: number;
}

/** Up to 3 playstyle tags for a build, from the aggregate function profile. */
export function deckTags(cards: DeckCardLine[], catalog: Catalog | null): string[] {
  if (catalog === null) return [];
  const fnCount: Record<string, number> = {};
  for (const c of cards) {
    const card = resolveDeckRow(catalog, { name: c.name });
    for (const f of card?.fn ?? []) fnCount[f] = (fnCount[f] ?? 0) + c.count;
  }
  const g = (k: string) => fnCount[k] ?? 0;
  // Note: gust (老大的指令) is near-universal, so it's not a distinguishing
  // selling-point — deliberately excluded from auto-tags.
  const candidates: DeckTag[] = [
    { key: "decks.tag.engine", weight: g("draw") + g("search") >= 6 ? g("draw") + g("search") : 0 },
    { key: "decks.tag.aggro", weight: g("attacker") + g("boost") >= 3 ? g("attacker") + g("boost") : 0 },
    { key: "decks.tag.accel", weight: g("accel") >= 3 ? g("accel") + 1 : 0 },
    { key: "decks.tag.disrupt", weight: g("disrupt") >= 2 ? g("disrupt") + 1 : 0 },
    { key: "decks.tag.durable", weight: g("heal") + g("protect") >= 3 ? g("heal") + g("protect") : 0 },
    { key: "decks.tag.recover", weight: g("recover") >= 2 ? g("recover") + 1 : 0 },
  ];
  return candidates
    .filter((c) => c.weight > 0)
    .sort((a, b) => b.weight - a.weight)
    .slice(0, 3)
    .map((c) => c.key);
}
