/**
 * Real archetype deck recommendations (docs/06 Phase 11) — generated by
 * scripts/fetch_decks.mjs from public Limitless tournament decklists. Served
 * as a lazy public/ asset; the math layer only ever reads count + isBasic.
 */

import type { NewCardInput } from "../state/deckStore.ts";
import { resolveDeckRow, type Catalog } from "./catalog.ts";

export interface DeckCardLine {
  count: number;
  /** zh-tw name where bridgeable, else the English/ja name (honest fallback). */
  name: string;
  isBasic: boolean;
  section: "pokemon" | "trainer" | "energy" | "unknown";
}

export interface DeckBuild {
  event: string;
  date: string;
  players: number;
  online: boolean;
  /** Final placing when known (null = not in the published top cut). */
  placing: number | null;
  total: number;
  cards: DeckCardLine[];
}

export interface Archetype {
  id: string;
  /** Limitless's own archetype name (English carry Pokémon). */
  name: string;
  icons: string[];
  deckCount: number;
  score: number;
  builds: DeckBuild[];
}

export interface DeckData {
  v: number;
  source: string;
  note: string;
  generatedFor: string;
  format: string;
  sampleDecks: number;
  tournaments: number;
  dateFrom: string | null;
  dateTo: string | null;
  archetypes: Archetype[];
}

let decksPromise: Promise<DeckData> | null = null;

export function loadDecks(): Promise<DeckData> {
  if (decksPromise === null) {
    decksPromise = fetch(`${import.meta.env.BASE_URL}catalog/decks-zh-Hant.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`decks HTTP ${res.status}`);
        return res.json() as Promise<DeckData>;
      })
      .catch((err: unknown) => {
        decksPromise = null;
        throw err;
      });
  }
  return decksPromise;
}

/** Test hook: inject (or clear) the deck data without a network call. */
export function setDecksForTests(data: DeckData | null): void {
  decksPromise = data === null ? null : Promise.resolve(data);
}

/** A build's 60 lines as deck-import inputs (math reads count + isBasic). */
export function buildToInputs(build: DeckBuild): NewCardInput[] {
  return build.cards.map((c) => ({
    name: c.name,
    count: c.count,
    isBasic: c.isBasic,
    section: c.section,
  }));
}

/** Field-size tier label (honest: by player count, not official rank). */
export function tierKey(players: number): string {
  if (players >= 128) return "decks.tier.large";
  if (players >= 64) return "decks.tier.mid";
  if (players >= 32) return "decks.tier.small";
  return "decks.tier.local";
}

// ---------------------------------------------------------------------------
// Archetype name localization (owner request 2026-06-14: 牌組推薦 titles must be
// zh in the zh UI). Limitless archetype names are space-separated English
// Pokémon (+ Mega / possessive prefixes / a few descriptors). Pokémon map via
// the official dex (catalog.dexEnZh); unknown tokens stay English (no guessing).

const ARCH_POSSESSIVE: Record<string, string> = {
  "n's": "N之",
  "rocket's": "火箭隊的",
  "team rocket's": "火箭隊的",
  "cynthia's": "竹蘭的",
  "hop's": "赫普的",
  "lillie's": "莉莉艾的",
  "misty's": "小霞的",
  "marnie's": "瑪俐的",
  "iono's": "奇樹的",
  "ethan's": "阿正的",
};
const ARCH_WORD: Record<string, string> = {
  box: "盒組",
  toolbox: "百寶箱",
  lead: "先手",
  basic: "基礎",
  control: "控場",
  mill: "磨牌",
  turbo: "渦輪",
  stall: "拖延",
};

/** Localize a Limitless archetype name to zh (Pokémon via the official dex). */
export function localizeArchetype(name: string, catalog: Catalog | null): string {
  const dex = catalog?.dexEnZh;
  if (dex === undefined) return name;
  const words = name.trim().split(/\s+/);
  const parts: string[] = [];
  let prefix = ""; // Mega / possessive that attaches to the next Pokémon
  for (let i = 0; i < words.length; i++) {
    const w = words[i] as string;
    const lw = w.toLowerCase();
    if (lw === "mega") {
      prefix += "超級";
      continue;
    }
    if (ARCH_POSSESSIVE[lw] !== undefined) {
      prefix += ARCH_POSSESSIVE[lw];
      continue;
    }
    // Try a two-word Pokémon (e.g. Raging Bolt, Iron Hands) then one word.
    const two = i + 1 < words.length ? `${lw} ${(words[i + 1] as string).toLowerCase()}` : "";
    if (two !== "" && dex[two] !== undefined) {
      parts.push(prefix + dex[two]);
      prefix = "";
      i += 1;
      continue;
    }
    if (dex[lw] !== undefined) {
      parts.push(prefix + dex[lw]);
      prefix = "";
      continue;
    }
    // Descriptor or unknown.
    parts.push(prefix + (ARCH_WORD[lw] ?? w));
    prefix = "";
  }
  if (prefix !== "") parts.push(prefix); // dangling Mega with no match
  return parts.join(" ");
}

// ---------------------------------------------------------------------------
// Humanized playstyle / selling-point tags, computed from the deck's REAL card
// functions (the classify() fn tags) — data-driven, not editorial.

export interface DeckTag {
  key: string; // i18n key
  weight: number;
}

/** Up to 3 playstyle tags for a build, from the aggregate function profile. */
export function deckTags(cards: DeckCardLine[], catalog: Catalog | null): string[] {
  if (catalog === null) return [];
  const fnCount: Record<string, number> = {};
  for (const c of cards) {
    const card = resolveDeckRow(catalog, { name: c.name });
    for (const f of card?.fn ?? []) fnCount[f] = (fnCount[f] ?? 0) + c.count;
  }
  const g = (k: string) => fnCount[k] ?? 0;
  // Note: gust (老大的指令) is near-universal, so it's not a distinguishing
  // selling-point — deliberately excluded from auto-tags.
  const candidates: DeckTag[] = [
    { key: "decks.tag.engine", weight: g("draw") + g("search") >= 6 ? g("draw") + g("search") : 0 },
    { key: "decks.tag.aggro", weight: g("attacker") + g("boost") >= 3 ? g("attacker") + g("boost") : 0 },
    { key: "decks.tag.accel", weight: g("accel") >= 3 ? g("accel") + 1 : 0 },
    { key: "decks.tag.disrupt", weight: g("disrupt") >= 2 ? g("disrupt") + 1 : 0 },
    { key: "decks.tag.durable", weight: g("heal") + g("protect") >= 3 ? g("heal") + g("protect") : 0 },
    { key: "decks.tag.recover", weight: g("recover") >= 2 ? g("recover") + 1 : 0 },
  ];
  return candidates
    .filter((c) => c.weight > 0)
    .sort((a, b) => b.weight - a.weight)
    .slice(0, 3)
    .map((c) => c.key);
}
